version: '3.4'
services:

  development:
    build: 
      context: .
      dockerfile: ../rust-fullstack-devcontainer/Dockerfile
    
    volumes:
      - ..:/vscode:cached
      - ~/.ssh:/home/host-ssh:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    working_dir: /vscode
    